---
language: python
services: docker

env:
  global:
    - ROLE_NAME: security
  matrix:
    - IMAGE="debian" TAG="latest"
    - IMAGE="debian" TAG="stretch"
    - IMAGE="ubuntu" TAG="latest"
    - IMAGE="ubuntu" TAG="bionic"
    - IMAGE="centos" TAG="latest"
    - IMAGE="centos" TAG="7"
    - IMAGE="fedora" TAG="latest"
    - IMAGE="fedora" TAG="31"
    - IMAGE="fedora" TAG="30"
    - IMAGE="archlinux" TAG="latest"

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
