---
- name: Install unattended upgrades package.
  package:
    name:
      - unattended-upgrades
      - apt-listchanges
      - mailutils
    state: present

- name: Copy unattended-upgrades configuration in the remote host.
  template:
    src: "etc/apt/apt.conf.d/{{ item }}.j2"
    dest: /etc/apt/apt.conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
