---
- name: Ensure dnf-automatic is installed.
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Copy dnf-automatic configuration to the remote host.
  ansible.builtin.template:
    src: /etc/dnf/automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure dnf-automatic.timer is running and enabled at boot.
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
