---
- name: Remove unnecessary DEB packages.
  apt:
    name: "{{ security_clean_deb_packages }}"
    state: absent
    purge: true
  when:
    - security_cleanup_deb_packages | length > 0
    - ansible_os_family == "Debian"

- name: Remove unnecessary RPM packages.
  yum:
    name: "{{ security_clean_rpm_packages }}"
    state: absent
  when:
    - security_cleanup_rpm_packages is defined
    - ansible_os_family == "RedHat"
