---
- name: Remove unnecessary DEB packages.
  apt:
    name: "{{ security_cleanup_deb_packages }}"
    state: absent
    purge: true
  when:
    - security_cleanup_deb_packages | length > 0
    - ansible_os_family == "Debian"

- name: Remove unnecessary RPM packages.
  yum:
    name: "{{ security_cleanup_rpm_packages }}"
    state: absent
  when:
    - security_cleanup_rpm_packages is defined
    - ansible_os_family == "RedHat"

- name: Remove unnecessary pacman packages.
  pacman:
    name: "{{ security_cleanup_pacman_packages }}"
    state: absent
    extra_args: --recursive
  when:
    - security_cleanup_pacman_packages is defined
    - ansible_os_family == "Archlinux"
