---
- name: Ensure required packages for fail2ban are installed.
  ansible.builtin.package:
    name: "{{ security_fail2ban_packages }}"
    state: present

- name: Copy fail2ban local jail to the remote host.
  ansible.builtin.template:
    src: etc/fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: SSH jail
  when: security_fail2ban_add_ssh_jail | bool
  block:
    - name: Copy fail2ban custom sshd jail to the remote host.
      ansible.builtin.template:
        src: etc/fail2ban/jail.d/sshd.local.j2
        dest: /etc/fail2ban/jail.d/sshd.local
        owner: root
        group: root
        mode: 0644

    - name: Ensure LogLevel is set to verbose for ssh.
      ansible.builtin.lineinfile:
        dest: "{{ security_ssh_config_path }}"
        regexp: "^LogLevel"
        line: "LogLevel VERBOSE"
        state: present
        backup: true
        validate: "sshd -T -f %s"
        mode: "0644"

- name: Additional fail2ban service hardening using systemd.
  when: security_fail2ban_harden_service | bool
  block:
    - name: Create /etc/systemd/system/fail2ban.service.d override directory.
      ansible.builtin.file:
        path: /etc/systemd/system/fail2ban.service.d
        state: directory
        mode: 0755

    - name: Copy the override template.
      ansible.builtin.template:
        src: etc/systemd/system/fail2ban.service.d/override.conf.j2
        dest: /etc/systemd/system/fail2ban.service.d/override.conf
        owner: root
        group: root
        mode: 0644

    - name: Adjust the "logtarget" path.
      ansible.builtin.template:
        src: etc/fail2ban/fail2ban.local.j2
        dest: /etc/fail2ban/fail2ban.local
        owner: root
        group: root
        mode: 0644

    - name: Create the /var/log/fail2ban/ directory.
      ansible.builtin.file:
        path: /var/log/fail2ban
        state: directory
        mode: 0755

    - name: Reload systemd daemon.
      ansible.builtin.systemd:
        daemon_reload: true

- name: Enable fail2ban at boot.
  ansible.builtin.service:
    name: fail2ban
    enabled: true
