---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Copy local jail configuration to the remote host.
  ansible.builtin.template:
    src: etc/fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: Install fail2ban-firewalld on RedHat systems
  ansible.builtin.dnf:
    name: fail2ban-firewalld
    state: present
  when:
    - security_fail2ban_use_firewalld_on_rhel | bool
    - ansible_os_family == "RedHat"

- name: Use firewalld as the banaction on RedHat-based systems
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/jail.local
    insertafter: "^[DEFAULT]"
    line: "{{ item }}"
  loop:
    - "banaction = firewallcmd-rich-rules[actiontype=<multiport>]"
    - "banaction_allports = firewallcmd-rich-rules[actiontype=<allports>]"
  when:
    - security_fail2ban_use_firewalld_on_rhel | bool
    - ansible_os_family == "RedHat"
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"

- name: Use systemd's journald as the logging backend
  ansible.builtin.template:
    src: etc/fail2ban/jail.d/systemd.conf.j2
    dest: /etc/fail2ban/jail.d/00-systemd.conf
    owner: root
    group: root
    mode: 0644

- name: SSH jail
  when: security_fail2ban_add_ssh_jail | bool
  block:
    - name: Copy fail2ban custom sshd jail to the remote host.
      ansible.builtin.template:
        src: etc/fail2ban/jail.d/sshd.local.j2
        dest: /etc/fail2ban/jail.d/sshd.local
        owner: root
        group: root
        mode: 0644

    - name: Ensure LogLevel is set to verbose for ssh.
      ansible.builtin.lineinfile:
        dest: "{{ security_ssh_config_path }}"
        regexp: "^LogLevel"
        line: "LogLevel VERBOSE"
        state: present
        backup: true
        validate: "sshd -T -f %s"
        mode: "0644"

- name: Ensure fail2ban is started and enabled on boot
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
    daemon_reload: true
