---
- name: Create limits.d directory if it doesn't exist.
  file:
    path: /etc/security/limits.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Disable core dumps.
  pam_limits:
    dest: /etc/security/limits.d/10-custom-limits.conf
    domain: "*"
    limit_type: hard
    limit_item: core
    value: "0"
    comment: Disable core dumps for all users since they can contain sensitive information.
