---
- name: Set distribution family specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: ssh.yml

- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

- include_tasks: cleanup-packages.yml

- include_tasks: sysctl.yml

- include_tasks: restrict-access.yml

- include_tasks: autoupdates-Debian.yml
  when:
    - ansible_os_family == "Debian"
    - security_autoupdates_enabled | bool

- include_tasks: autoupdates-RedHat.yml
  when:
    - ansible_os_family == "RedHat"
    - security_autoupdates_enabled | bool

- include_tasks: pam-RedHat.yml
  when:
    - security_secure_pam | bool
    - ansible_os_family == "RedHat"

- include_tasks: pam-Debian.yml
  when:
    - security_secure_pam | bool
    - ansible_os_family == "Debian"

- include_tasks: limits.yml
  when:
    - security_secure_pam | bool
