---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Set distribution specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks for SSH hardening
  ansible.builtin.include_tasks: ssh.yml

- name: Include tasks for setting up fail2ban
  ansible.builtin.include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool
#
- name: Include tasks for kernel hardening via sysctl
  ansible.builtin.include_tasks: sysctl.yml
  when:
    - ansible_connection != "docker"
    - ansible_connection != "podman"
    - ansible_connection != "container"

- name: Include tasks for setting up automatic updates
  ansible.builtin.include_tasks: autoupdates-{{ ansible_os_family }}.yml
  when: security_autoupdates_enabled | bool

- name: Include tasks for removing unneccessary packages
  ansible.builtin.include_tasks: cleanup-packages.yml

- name: Include tasks for restricting access to kernel processes and core dumps
  ansible.builtin.include_tasks: restrict.yml
