---
- name: Set distribution family specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: ssh.yml

- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

- include_tasks: cleanup-packages.yml

- include_tasks: sysctl.yml

- include_tasks: restrict-access.yml

- include_tasks: autoupdates-{{ ansible_os_family }}.yml
  when: security_autoupdates_enabled | bool

- include_tasks: pam-{{ ansible_os_family }}.yml
  when: security_secure_pam | bool

- include_tasks: limits.yml
  when:
    - security_secure_pam | bool
