---
- name: Set distribution family specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: ssh.yml

- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

- include_tasks: cleanup-packages.yml

- include_tasks: sysctl.yml
  when:
    - ansible_connection != "docker"
    - ansible_connection != "podman"
    - ansible_connection != "container"

- include_tasks: restrict-access.yml
  when:
    - (security_kern_hidepid_value | int == 1) or (security_kern_hidepid_value | int == 2)
    - security_kern_hidepid_mount_opts is defined

- include_tasks: autoupdates-{{ ansible_os_family }}.yml
  when:
    - security_autoupdates_enabled | bool
    - not ansible_os_family == "Archlinux"

- include_tasks: pam-{{ ansible_os_family }}.yml
  when: security_secure_pam | bool

- include_tasks: limits.yml
  when:
    - security_secure_pam | bool
