---
- name: Enforce users to use strong passwords (Debian systems).
  block:
    - name: Install libpam-pwquality.
      apt:
        name: libpam-pwquality
        update_cache: true
        state: present

    - name: Update pwquality module arguments.
      pamd:
        name: common-password
        type: password
        control: "requisite"
        module_path: pam_pwquality.so
        module_arguments: " retry=3
          minlen=12
          lcredit=-1
          ucredit=-1
          dcredit=-1
          ocredit=-1
          enforce_for_root"
        state: args_present
        backup: true
  when: security_enforce_strong_passwords | bool

- name: Lock user account after three failed login attempts (Debian systems).
  pamd:
    name: common-auth
    type: auth
    control: "[success=1 default=ignore]"
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_tally2.so
    module_arguments: "onerr=fail deny=3 unlock_time=1800"
    state: before
  when: security_lock_after_failed_logins | bool
