---
- name: Enforce users to use strong passwords (RedHat systems).
  pamd:
    name: system-auth
    type: password
    control: "requisite"
    module_path: pam_pwquality.so
    module_arguments: "try_first_pass
      local_users_only
      retry=3
      authok_type=
      minlen=12
      lcredit=-1
      ucredit=-1
      dcredit=-1
      ocredit=-1
      enforce_for_root"
    state: args_present
    backup: true
  when: security_enforce_strong_passwords | bool

- name: Lock user account after three failed login attempts (RedHat systems).
  block:
    - name: pam_faillock - system-auth [ auth - required ]
      lineinfile:
        path: /etc/pam.d/system-auth
        insertafter: '^auth\s*required\s*pam_env\.so'
        line: "auth   required    pam_faillock.so preauth silent audit deny=4"
        backup: true
        mode: "0644"
    - name: pam_faillock - system-auth [ auth - default=die ]
      lineinfile:
        path: /etc/pam.d/system-auth
        insertafter: '^auth\s*sufficient\s*pam_unix\.so\s*nullok\s*try_first_pass'
        line: "auth   [default=die]    pam_faillock.so authfail audit deny=4"
        backup: true
        mode: "0644"
    - name: pam_faillock - system-auth [ account - default=die ]
      lineinfile:
        path: /etc/pam.d/system-auth
        insertafter: "^account.*"
        line: "account   required    pam_faillock.so"
        backup: true
        mode: "0644"
    - name: pam_faillock - password-auth [ auth - required ]
      lineinfile:
        path: /etc/pam.d/password-auth
        insertafter: '^auth\s*required\s*pam_env\.so'
        line: "auth   required    pam_faillock.so preauth silent audit deny=4"
        backup: true
        mode: "0644"
    - name: pam_faillock - password-auth [ auth - default=die ]
      lineinfile:
        path: /etc/pam.d/password-auth
        insertafter: '^auth\s*sufficient\s*pam_unix\.so\s*nullok\s*try_first_pass'
        line: "auth   [default=die]    pam_faillock.so authfail audit deny=4"
        backup: true
        mode: "0644"
    - name: pam_faillock - password-auth [ account - default=die ]
      lineinfile:
        path: /etc/pam.d/password-auth
        insertafter: "^account.*"
        line: "account   required    pam_faillock.so"
        backup: true
        mode: "0644"
  when: security_lock_after_failed_logins | bool
