---
- name: Use hidepid to hide processes from users.
  mount:
    path: /proc
    src: proc
    fstype: proc
    opts: "{{ security_kern_hidepid_mount_opts }}"
    state: present

- name: Fix user sessions after mounting /proc with hidepid.
  block:
    - name: Add systemd-logind exception | Ensure /etc/systemd/system/systemd-logind.service.d exists.
      ansible.builtin.file:
        path: /etc/systemd/system/systemd-logind.service.d
        state: directory
        mode: '0755'

    - name: Add systemd-logind exception | Write hidepid.conf.
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/systemd-logind.service.d/hidepid.conf
        create: true
        mode: "0644"
        block: |
          [Service]
          SupplementaryGroups=proc
