---
- name: Hide kernel processes
  when:
    - (security_kern_hidepid_value | int == 1) or (security_kern_hidepid_value | int == 2)
    - security_kern_hidepid_mount_opts is defined
  block:
    - name: Use hidepid to hide processes from users.
      ansible.posix.mount:
        path: /proc
        src: proc
        fstype: proc
        opts: "{{ security_kern_hidepid_mount_opts }}"
        state: present

    - name: Fix user sessions after mounting /proc with hidepid.
      block:
        - name: Add systemd-logind exception | Ensure /etc/systemd/system/systemd-logind.service.d exists.
          ansible.builtin.file:
            path: /etc/systemd/system/systemd-logind.service.d
            state: directory
            mode: '0755'

        - name: Add systemd-logind exception | Write hidepid.conf.
          ansible.builtin.blockinfile:
            path: /etc/systemd/system/systemd-logind.service.d/hidepid.conf
            create: true
            mode: "0644"
            block: |
              [Service]
              SupplementaryGroups=proc

- name: Core dumps
  when: security_disable_core_dumps | bool
  block:
    - name: Create limits.d directory if it doesn't exist.
      ansible.builtin.file:
        path: /etc/security/limits.d
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Disable core dumps.
      community.general.pam_limits:
        dest: /etc/security/limits.d/10-custom-limits.conf
        domain: "*"
        limit_type: hard
        limit_item: core
        value: "0"
        comment: Disable core dumps for all users since they can contain sensitive information.
