---
- name: Use hidepid to hide processes from users.
  mount:
    path: /proc
    src: proc
    fstype: proc
    opts: "{{ security_kern_hidepid_mount_opts }}"
    state: present
  when:
    - (security_kern_hidepid_value | int == 1) or (security_kern_hidepid_value | int == 2)
    - security_kern_hidepid_mount_opts is defined
