---
- name: Ensure required packages for configuring sysctl are installed.
  ansible.builtin.package:
    name: "{{ procps_package_name }}"
    state: present

- name: Ensure the /etc/sysctl.d/ directory exists.
  ansible.builtin.file:
    path: /etc/sysctl.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Kernel hardening using sysctl options.
  ansible.builtin.include_tasks: sysctl-kernel.yml
  when: security_kern_go_hardcore | bool

- name: TCP/IP stack hardening using sysctl options.
  ansible.builtin.include_tasks: sysctl-tcp_ip_stack.yml
  when: security_net_go_hardcore | bool
