---
- name: Converge
  hosts: all

  vars:
    security_cleanup_deb_packages:
      - xinetd
      - telnet-server
    security_cleanup_rpm_packages:
      - xinetd
      - telnet-server

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Ensure required packages are installed (RedHat).
      ansible.builtin.yum:
        name:
          - openssh-server
          - openssh-clients
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install EPEL repo (RedHat-based systems).
      ansible.builtin.yum:
        name: epel-release
        state: present
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution != "Fedora"

    - name: Ensure required packages are installed (Debian).
      ansible.builtin.apt:
        name:
          - openssh-server
          - openssh-client
        state: present
      when: ansible_os_family == "Debian"

    - name: Update pacman cache.
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"

    - name: Ensure required packages are installed (ArchLinux).
      pacman:
        name: openssh
        state: present
      when: ansible_os_family == "Archlinux"

    - name: Create SSH keys.
      block:
        - name: RSA keys.
          openssh_keypair:
            path: /etc/ssh/ssh_host_rsa_key
            type: rsa
        - name: DSA keys.
          openssh_keypair:
            path: /etc/ssh/ssh_host_dsa_key
            type: dsa
        - name: ECDSA keys.
          openssh_keypair:
            path: /etc/ssh/ssh_host_ecdsa_key
            type: ecdsa

  tasks:
    - name: "Include hardening"
      ansible.builtin.include_role:
        name: "ansible-role-security"
